import { readFile } from 'node:fs/promises';
import { writeJson } from './shared.ts';

type TobaccoRecord = { sourceResourceYear?: number; legalVersion: string; districtName: string; inspectionCategory: string; normalizedCategory: string; inspectionCount?: number };
const records = JSON.parse(await readFile('public/data/tobacco-control-inspection-results/records.json', 'utf8')) as TobaccoRecord[];
const counted = records.filter((record) => record.inspectionCount !== undefined) as Array<TobaccoRecord & { inspectionCount: number }>;
const group = <T extends string | number>(items: typeof counted, key: (item: typeof counted[number]) => T) => Object.entries(items.reduce<globalThis.Record<string, number>>((result, item) => { const value = String(key(item)); result[value] = (result[value] ?? 0) + item.inspectionCount; return result; }, {})).map(([name, inspectionCount]) => ({ name, inspectionCount })).sort((a, b) => b.inspectionCount - a.inspectionCount);
const years = [...new Set(records.flatMap((record) => record.sourceResourceYear ? [record.sourceResourceYear] : []))].sort((a, b) => a - b);
const byDistrict = group(counted.filter((record) => record.districtName !== '臺北市（全市）'), (record) => record.districtName || 'unknown');
const byCategory = group(counted, (record) => record.inspectionCategory);
await writeJson('public/data/tobacco-control-inspection-results/summary.json', { generatedAt: new Date().toISOString(), latestAvailableYear: years.at(-1), totalInspectionCount: counted.reduce((sum, record) => sum + record.inspectionCount, 0), districtsCovered: new Set(records.map((record) => record.districtName).filter((district) => district && district !== '臺北市（全市）')).size, inspectionCategories: new Set(records.map((record) => record.inspectionCategory)).size, largestDistrictTotal: byDistrict[0], mostCommonInspectionCategory: byCategory[0], oldLawRecordCount: records.filter((record) => record.legalVersion === 'old_law').length, amendedLawRecordCount: records.filter((record) => record.legalVersion === 'amended_law').length, byDistrict, byCategory, byYear: group(counted, (record) => record.sourceResourceYear ?? 'unknown'), byLegalVersion: group(counted, (record) => record.legalVersion), comparability: 'Old-law and amended-law categories are presented separately. Only source fields with an explicitly documented equivalent mapping may be combined.' });
