import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { decodeCsvBuffer, parseCsv, writeJson } from './shared.ts';

const sourcePageUrl='https://data.taipei/dataset/detail?id=d3f0c616-c57b-4f70-96b4-9c9fa1cfa080';
const [header=[],...rows]=parseCsv(decodeCsvBuffer(await readFile('data/raw/alcohol-tobacco-business-inspections/records.csv')));
const columns=header.map(x=>x.replace(/^\uFEFF/,'').trim()); const field=(name:string)=>columns.indexOf(name);
const f={month:field('統計月份'),monthly:field('當月抽檢家數'),cumulative:field('當年度累計抽檢家數'),manufacturer:field('製造業者'),importer:field('進口業者'),retailer:field('販賣業者'),undenatured:field('未變性酒精業者')};
if(Object.values(f).some(index=>index<0))throw new Error(`Unexpected tobacco/alcohol CSV schema: ${columns.join(', ')}`);
const value=(row:string[],index:number)=>row[index]?.trim()??''; const hash=(input:unknown)=>createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,16);
const integer=(raw:string)=>/^\d+$/.test(raw.replace(/[\s,]/g,''))?Number(raw.replace(/[\s,]/g,'')):null;
const parsePeriod=(raw:string)=>{const match=raw.match(/^(\d{3,4})(\d{2})$/);if(!match)return{year:null,month:null,period:null};let year=Number(match[1]);if(year<1911)year+=1911;const month=Number(match[2]);return month>=1&&month<=12?{year,month,period:`${year}-${String(month).padStart(2,'0')}`}:{year:null,month:null,period:null}};
const seen=new Set<string>(); const duplicateRows:string[]=[];
const records=rows.filter(row=>row.some(cell=>cell.trim())).flatMap((row,rowIndex)=>{const originalValues=Object.fromEntries(columns.map((name,index)=>[name,value(row,index)]));const signature=JSON.stringify(originalValues);if(seen.has(signature)){duplicateRows.push(String(rowIndex+2));return[]}seen.add(signature);const p=parsePeriod(value(row,f.month));const monthlyRaw=value(row,f.monthly),monthly=integer(monthlyRaw),cumulativeRaw=value(row,f.cumulative),cumulative=integer(cumulativeRaw),manufacturersRaw=value(row,f.manufacturer),manufacturers=integer(manufacturersRaw),importersRaw=value(row,f.importer),importers=integer(importersRaw),retailersRaw=value(row,f.retailer),retailers=integer(retailersRaw),undenaturedAlcoholBusinessesRaw=value(row,f.undenatured),undenaturedAlcoholBusinesses=integer(undenaturedAlcoholBusinessesRaw);const categories=[manufacturers,importers,retailers,undenaturedAlcoholBusinesses],categoryTotal=categories.every(x=>x!==null)?categories.reduce((sum,x)=>sum+(x??0),0):null;const warnings=[!p.period&&'invalidStatisticalMonth',monthlyRaw&&monthly===null&&'malformedMonthlyCount',cumulativeRaw&&cumulative===null&&'malformedCumulativeCount',categories.some(x=>x===null)&&'missingOrMalformedCategory',categoryTotal!==null&&monthly!==null&&categoryTotal!==monthly&&'categoryTotalMismatch'].filter(Boolean) as string[];return[{id:p.period?`alcohol-tobacco-${p.period}`:`alcohol-tobacco-${hash(originalValues)}`,module:'alcohol_tobacco_business_inspections',statisticalMonthRaw:value(row,f.month),year:p.year,month:p.month,period:p.period,monthlyInspectedBusinessesRaw:monthlyRaw,monthlyInspectedBusinesses:monthly,annualCumulativeInspectionsRaw:cumulativeRaw,annualCumulativeInspections:cumulative,manufacturersRaw,manufacturers,importersRaw,importers,retailersRaw,retailers,undenaturedAlcoholBusinessesRaw,undenaturedAlcoholBusinesses,calculatedCategoryTotal:categoryTotal,categoryTotalMatchesMonthlyTotal:categoryTotal!==null&&monthly!==null?categoryTotal===monthly:null,hasValidPeriod:!!p.period,hasValidMonthlyTotal:monthly!==null,dataQualityWarnings:warnings,originalValues,sourceRowNumber:rowIndex+2}];});
for(const year of [...new Set(records.map(r=>r.year).filter((x):x is number=>x!==null))]){let prior:number|null=null;for(const record of records.filter(r=>r.year===year).sort((a,b)=>(a.month??0)-(b.month??0))){if(prior!==null&&record.annualCumulativeInspections!==null&&record.annualCumulativeInspections<prior)record.dataQualityWarnings.push('cumulativeDecreasedWithinYear');if(prior!==null&&record.annualCumulativeInspections!==null&&record.monthlyInspectedBusinesses!==null&&record.annualCumulativeInspections-prior!==record.monthlyInspectedBusinesses)record.dataQualityWarnings.push('cumulativeDeltaMismatch');if(record.annualCumulativeInspections!==null)prior=record.annualCumulativeInspections}}
const duplicateMonths=Object.values(records.reduce<Record<string,number>>((all,record)=>{if(record.period)all[record.period]=(all[record.period]??0)+1;return all},{})).filter(count=>count>1).length;
const quality={inputRows:rows.filter(row=>row.some(cell=>cell.trim())).length,outputRows:records.length,duplicateSourceRows:duplicateRows.length,invalidStatisticalMonth:records.filter(r=>r.dataQualityWarnings.includes('invalidStatisticalMonth')).length,duplicateMonths,missingMonthlyInspectionCount:records.filter(r=>r.monthlyInspectedBusinesses===null).length,malformedCounts:records.filter(r=>r.dataQualityWarnings.some(x=>x.startsWith('malformed'))).length,missingOrMalformedCategory:records.filter(r=>r.dataQualityWarnings.includes('missingOrMalformedCategory')).length,categoryTotalMismatch:records.filter(r=>r.dataQualityWarnings.includes('categoryTotalMismatch')).length,cumulativeDecreasedWithinYear:records.filter(r=>r.dataQualityWarnings.includes('cumulativeDecreasedWithinYear')).length,cumulativeDeltaMismatch:records.filter(r=>r.dataQualityWarnings.includes('cumulativeDeltaMismatch')).length,recordsWithWarnings:records.filter(r=>r.dataQualityWarnings.length).length};
await writeJson('public/data/alcohol-tobacco-business-inspections/records.json',records.sort((a,b)=>(a.period??'').localeCompare(b.period??'')));
await writeJson('public/data/alcohol-tobacco-business-inspections/metadata.json',{module:'alcohol_tobacco_business_inspections',datasetId:'d3f0c616-c57b-4f70-96b4-9c9fa1cfa080',datasetTitle:'臺北市政府財政局年度各月份菸酒業者抽檢情形',resourceTitle:'臺北市政府財政局_年度各月份菸酒業者抽檢情形',sourcePageUrl,sourceAgency:'臺北市政府財政局',updateFrequency:'每2月 / Every two months',sourceFileUpdatedAt:'2026-08-06T10:19:20+08:00',metadataUpdatedAt:'2026-08-06T10:20:24+08:00',fields:columns,dataQuality:quality,limitations:'Aggregate inspection activity only; it does not identify businesses, violations, penalties, compliance, consumer risk, or geographic risk.'});
console.log(`Converted ${records.length} tobacco and alcohol inspection records.`);
