import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { decodeCsvBuffer, parseCsv, writeJson } from './shared.ts';

const sourcePageUrl='https://data.taipei/dataset/detail?id=e7b8404d-3742-4157-98fd-e101b40ba5c7';
const [header=[],...rows]=parseCsv(decodeCsvBuffer(await readFile('data/raw/soil-water-conservation-violations/records.csv')));
const columns=header.map(x=>x.replace(/^\uFEFF/,'').trim()); const field=(name:string)=>columns.indexOf(name);
const f={caseNumber:field('違規案件編號'),date:field('處分日期'),status:field('案件狀態'),district:field('地籍_區'),section:field('地籍_段'),subsection:field('地籍_小段'),lot:field('地籍_地號'),area:field('違規面積_平方公尺'),type:field('違規類別'),suspension:field('暫停開發兩年'),expiry:field('暫停開發到期日'),fine:field('罰鍰金額')};
if(Object.values(f).some(x=>x<0))throw new Error(`Unexpected soil-water CSV schema: ${columns.join(', ')}`);
const value=(row:string[],index:number)=>row[index]?.trim()??''; const hash=(x:unknown)=>createHash('sha256').update(JSON.stringify(x)).digest('hex').slice(0,16);
const parseDate=(raw:string)=>{const m=raw.match(/^(\d{3,4})[/-](\d{1,2})[/-](\d{1,2})$/);if(!m)return null;let year=Number(m[1]);if(year<1911)year+=1911;const month=Number(m[2]),day=Number(m[3]);const iso=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return month>=1&&month<=12&&day>=1&&day<=31&&!Number.isNaN(Date.parse(`${iso}T00:00:00Z`))?iso:null};
const parseAmount=(raw:string)=>{const cleaned=raw.replace(/[,$NT nt元\s]/g,'');return /^\d+(\.\d+)?$/.test(cleaned)&&Number(cleaned)>=0?Number(cleaned):null};
const seen=new Set<string>(); const duplicateRows:string[]=[];
const records=rows.filter(row=>row.some(x=>x.trim())).flatMap((row,rowIndex)=>{const originalValues=Object.fromEntries(columns.map((name,index)=>[name,value(row,index)]));const sig=JSON.stringify(originalValues);if(seen.has(sig)){duplicateRows.push(String(rowIndex+2));return[]}seen.add(sig);const caseNumber=value(row,f.caseNumber),dispositionDateRaw=value(row,f.date),dispositionDate=parseDate(dispositionDateRaw),violationAreaRaw=value(row,f.area),violationAreaSqm=parseAmount(violationAreaRaw),fineAmountRaw=value(row,f.fine),fineAmountTwd=parseAmount(fineAmountRaw),developmentSuspensionRaw=value(row,f.suspension),suspensionExpiryDateRaw=value(row,f.expiry),suspensionExpiryDate=parseDate(suspensionExpiryDateRaw),cadastralDistrict=value(row,f.district),cadastralSection=value(row,f.section),cadastralSubsection=value(row,f.subsection),cadastralLotNumber=value(row,f.lot),caseStatusRaw=value(row,f.status),violationTypeRaw=value(row,f.type);const warnings=[!caseNumber&&'missingCaseNumber',dispositionDateRaw&&!dispositionDate&&'invalidDispositionDate',!caseStatusRaw&&'missingStatus',!cadastralDistrict&&'missingCadastralDistrict',!cadastralLotNumber&&'missingLotNumber',violationAreaRaw&&violationAreaSqm===null&&'malformedViolationArea',fineAmountRaw&&fineAmountTwd===null&&'malformedFineAmount',suspensionExpiryDateRaw&&!suspensionExpiryDate&&'invalidSuspensionExpiryDate',suspensionExpiryDate&&!developmentSuspensionRaw&&'expiryWithoutRecordedSuspension'].filter(Boolean) as string[];const cadastralReference=[cadastralDistrict&&`${cadastralDistrict}區`,cadastralSection&&`${cadastralSection}段`,cadastralSubsection&&`${cadastralSubsection}小段`,cadastralLotNumber&&`${cadastralLotNumber}地號`].filter(Boolean).join('');return[{id:caseNumber?`soil-water-${caseNumber}`:`soil-water-${hash(originalValues)}`,module:'soil_water_conservation_violations',caseNumber,dispositionDateRaw,dispositionDate,dispositionYear:dispositionDate?Number(dispositionDate.slice(0,4)):null,caseStatusRaw,caseStatus:caseStatusRaw||'unknown',cadastralDistrict,cadastralSection,cadastralSubsection,cadastralLotNumber,cadastralReference,violationAreaRaw,violationAreaSqm,violationTypeRaw,violationType:violationTypeRaw||'unknown',developmentSuspensionRaw,hasTwoYearDevelopmentSuspension:developmentSuspensionRaw==='是'?true:developmentSuspensionRaw?false:null,suspensionExpiryDateRaw,suspensionExpiryDate,fineAmountRaw,fineAmountTwd,hasValidArea:violationAreaSqm!==null,hasValidFine:fineAmountTwd!==null,dataQualityWarnings:warnings,originalValues,sourceRowNumber:rowIndex+2}];});
const duplicates=(values:string[])=>Object.entries(values.reduce<Record<string,number>>((a,x)=>{if(x)a[x]=(a[x]??0)+1;return a},{})).filter(([,n])=>n>1).length;
const quality={inputRows:rows.filter(row=>row.some(x=>x.trim())).length,outputRows:records.length,exactDuplicateRows:duplicateRows.length,missingCaseNumber:records.filter(x=>!x.caseNumber).length,invalidDispositionDate:records.filter(x=>x.dataQualityWarnings.includes('invalidDispositionDate')).length,missingStatus:records.filter(x=>x.dataQualityWarnings.includes('missingStatus')).length,missingCadastralDistrict:records.filter(x=>x.dataQualityWarnings.includes('missingCadastralDistrict')).length,missingLotNumber:records.filter(x=>x.dataQualityWarnings.includes('missingLotNumber')).length,malformedViolationArea:records.filter(x=>x.dataQualityWarnings.includes('malformedViolationArea')).length,malformedFineAmount:records.filter(x=>x.dataQualityWarnings.includes('malformedFineAmount')).length,invalidSuspensionExpiryDate:records.filter(x=>x.dataQualityWarnings.includes('invalidSuspensionExpiryDate')).length,expiryWithoutRecordedSuspension:records.filter(x=>x.dataQualityWarnings.includes('expiryWithoutRecordedSuspension')).length,duplicateCaseNumbers:duplicates(records.map(x=>x.caseNumber)),recordsWithWarnings:records.filter(x=>x.dataQualityWarnings.length).length};
await writeJson('public/data/soil-water-conservation-violations/records.json',records);
await writeJson('public/data/soil-water-conservation-violations/metadata.json',{module:'soil_water_conservation_violations',datasetId:'e7b8404d-3742-4157-98fd-e101b40ba5c7',datasetTitle:'臺北市水土保持法違規案件',resourceTitle:'水土保持法違規案件詳情',sourcePageUrl,sourceAgency:'臺北市政府工務局大地工程處',sourceFileUpdatedAt:'2025-03-13T16:44:52+08:00',metadataUpdatedAt:'2026-04-07T09:39:35+08:00',coverageStart:'1996-01-05',coverageEnd:'2022-12-31',historical:true,fields:columns,dataQuality:quality,limitations:'Historical enforcement records. They do not establish a parcel’s current legal status, development eligibility, ownership, safety, or unpaid-fine balance.'});
console.log(`Converted ${records.length} soil and water conservation violation records.`);
