import { useEffect, useMemo, useState } from 'react';
import type { Language } from './types';

type RecordItem = { id:string; facilityName:string; address:string; materialCategory:string; phone:string };
const t = (language:Language, zh:string, en:string) => language === 'zh' ? zh : en;

export default function AntivenomStockpiles({language}:{language:Language}) {
  const [records,setRecords]=useState<RecordItem[]>([]); const [query,setQuery]=useState('');
  useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/antivenom-stockpiles/approximate-district-records.json`).then(response=>response.json()).then(setRecords);},[]);
  const rows=useMemo(()=>records.filter(record=>[record.facilityName,record.address,record.materialCategory].join(' ').toLowerCase().includes(query.toLowerCase())),[records,query]);
  return <main className="overview appeal-trends"><section className="hero"><p className="eyebrow">{t(language,'醫療資源 · 公開清冊','Medical Resources · Public Directory')}</p><h2>{t(language,'抗蛇毒血清儲備點','Antivenom Stockpile Locations')}</h2><p className="notice">{t(language,'抗蛇毒血清庫存可能變動，本清冊不是即時可用性資訊；疑似蛇咬應立即就醫。','Antivenom stock may change. This directory is not real-time availability information; suspected snakebite requires immediate medical attention.')}</p></section><section className="filter-panel health-filters"><label className="search-field">{t(language,'搜尋','Search')}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t(language,'醫療機構、地址或血清種類','Facility, address, or antivenom type')}/></label></section><section className="summary-grid"><article className="metric"><span>{t(language,'符合條件的儲備點','Matching stockpile locations')}</span><strong>{rows.length}</strong></article><article className="metric"><span>{t(language,'血清種類','Antivenom categories')}</span><strong>{new Set(rows.map(record=>record.materialCategory).filter(Boolean)).size}</strong></article></section><section className="directory-card-grid">{rows.map(record=><article className="panel directory-card" key={record.id}><h3>{record.facilityName}</h3><dl><div><dt>{t(language,'血清種類','Antivenom type')}</dt><dd>{record.materialCategory||'—'}</dd></div><div><dt>{t(language,'地址','Address')}</dt><dd>{record.address||'—'}</dd></div><div><dt>{t(language,'電話','Telephone')}</dt><dd>{record.phone?<a href={`tel:${record.phone}`}>{record.phone}</a>:'—'}</dd></div></dl><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.address)}`}>{t(language,'外部地圖查詢','External map lookup')}</a></article>)}</section></main>;
}
