import { useEffect, useMemo, useState } from 'react';
import type { Language } from './types';
type RecordItem = { id: string; sourceSequenceNumber: string; inspectionDateRaw: string; inspectionDate: string | null; inspectionYear: number | null; vendorName: string; productName: string; laboratoryResultRaw: string; laboratoryResult: string; labelingRegistrationResultRaw: string; labelingRegistrationResult: string; originalValues: Record<string, string> };
const base = `${import.meta.env.BASE_URL}data/cosmetics-inspection-results/`;
const displayResult = (value: string) => value === 'compliant' ? 'Compliant' : value === 'non_compliant' ? 'Non-compliant' : value === 'other' ? 'Other' : 'Unknown';
export default function CosmeticsInspectionResults({ language }: { language: Language }) {
  const [records, setRecords] = useState<RecordItem[]>([]); const [query, setQuery] = useState(''); const [year, setYear] = useState('all'); const [lab, setLab] = useState('all');
  useEffect(() => { fetch(base + 'records.json').then(response => response.json()).then(setRecords); }, []);
  const rows = useMemo(() => records.filter(record => (year === 'all' || String(record.inspectionYear) === year) && (lab === 'all' || record.laboratoryResult === lab) && [record.sourceSequenceNumber, record.vendorName, record.productName, record.laboratoryResultRaw, record.labelingRegistrationResultRaw].join(' ').toLowerCase().includes(query.toLowerCase())), [records, year, lab, query]);
  const years = [...new Set(records.map(record => record.inspectionYear).filter((value): value is number => value !== null))].sort();
  const download = () => { const csv = [['ID', 'Inspection date', 'Source vendor', 'Product', 'Laboratory result', 'Labeling / registration result'], ...rows.map(record => [record.sourceSequenceNumber, record.inspectionDateRaw, record.vendorName, record.productName, record.laboratoryResultRaw, record.labelingRegistrationResultRaw])].map(row => row.map(value => `"${value.replaceAll('"', '""')}"`).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv' })); anchor.download = 'cosmetics-inspection-results.csv'; anchor.click(); };
  return <main className="overview appeal-trends"><section className="hero"><p className="eyebrow">Public Health · Product Safety · Inspection</p><h2>{language === 'zh' ? '化粧品抽驗結果' : 'Cosmetics Inspection Results'}</h2><p className="notice">{language === 'zh' ? '每筆資料為特定時間的抽驗紀錄，不代表產品目前狀態或所有化粧品的整體情形。' : 'Each entry is an inspection record at a particular time; it does not establish current product status or represent all cosmetics.'}</p></section><section className="filter-panel"><label>{language === 'zh' ? '年度' : 'Year'}<select value={year} onChange={event => setYear(event.target.value)}><option value="all">All</option>{years.map(value => <option key={value}>{value}</option>)}</select></label><label>{language === 'zh' ? '檢驗結果' : 'Laboratory result'}<select value={lab} onChange={event => setLab(event.target.value)}><option value="all">All</option>{['compliant', 'non_compliant', 'other', 'unknown'].map(value => <option key={value} value={value}>{displayResult(value)}</option>)}</select></label><label className="search-field">{language === 'zh' ? '搜尋' : 'Search'}<input value={query} onChange={event => setQuery(event.target.value)} placeholder={language === 'zh' ? '產品、來源廠商、結果或序號' : 'Product, source vendor, result, or ID'} /></label></section><section className="summary-grid">{[['Inspection records', rows.length], ['Unique products', new Set(rows.map(record => record.productName)).size], ['Source vendors', new Set(rows.map(record => record.vendorName)).size], ['Compliant laboratory records', rows.filter(record => record.laboratoryResult === 'compliant').length], ['Non-compliant laboratory records', rows.filter(record => record.laboratoryResult === 'non_compliant').length], ['Latest inspection', rows.map(record => record.inspectionDate).filter((value): value is string => Boolean(value)).sort().at(-1) ?? '—']].map(([name, value]) => <article className="metric" key={String(name)}><span>{name}</span><strong>{String(value)}</strong></article>)}</section><section className="panel table-wrap"><button onClick={download}>{language === 'zh' ? '下載篩選 CSV' : 'Download filtered CSV'}</button><table><thead><tr>{['ID', 'Inspection date', 'Source vendor', 'Product', 'Laboratory result', 'Labeling / registration result'].map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(record => <tr key={record.id}><td>{record.sourceSequenceNumber || '—'}</td><td>{record.inspectionDate ?? record.inspectionDateRaw ?? '—'}</td><td>{record.vendorName || '—'}</td><td><details><summary>{record.productName || '—'}</summary><pre>{JSON.stringify(record.originalValues, null, 2)}</pre></details></td><td>{record.laboratoryResultRaw || '—'} ({displayResult(record.laboratoryResult)})</td><td>{record.labelingRegistrationResultRaw || '—'} ({displayResult(record.labelingRegistrationResult)})</td></tr>)}</tbody></table></section></main>;
}
