import { useEffect, useMemo, useState } from 'react';
import type { Language } from './types';

type RecordItem={id:string;name:string;address:string;level:string};
const t=(language:Language,zh:string,en:string)=>language==='zh'?zh:en;

export default function DiabetesHealthInstitutions({language}:{language:Language}) {
  const[records,setRecords]=useState<RecordItem[]>([]);const[query,setQuery]=useState('');const[level,setLevel]=useState('all');
  useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/diabetes-health-institutions/approximate-district-records.json`).then(response=>response.json()).then(setRecords);},[]);
  const levels=[...new Set(records.map(record=>record.level).filter(Boolean))].sort();
  const rows=useMemo(()=>records.filter(record=>(level==='all'||record.level===level)&&[record.name,record.address].join(' ').toLowerCase().includes(query.toLowerCase())),[records,level,query]);
  return <main className="overview appeal-trends"><section className="hero"><p className="eyebrow">{t(language,'健康促進 · 醫療機構清冊','Health Promotion · Institution Directory')}</p><h2>{t(language,'糖尿病健康促進機構','Diabetes Health Promotion Institutions')}</h2><p className="notice">{t(language,'來源地址未提供權威座標；本清冊提供外部文字地圖查詢，不繪製推測位置，也不代表即時服務可用性。','Source addresses have no authoritative coordinates. This directory provides external text map lookup, does not plot inferred locations, and does not establish real-time service availability.')}</p></section><section className="filter-panel health-filters"><label>{t(language,'機構層級','Institution level')}<select value={level} onChange={event=>setLevel(event.target.value)}><option value="all">{t(language,'全部','All')}</option>{levels.map(value=><option key={value}>{value}</option>)}</select></label><label className="search-field">{t(language,'搜尋','Search')}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t(language,'機構名稱或地址','Institution or address')}/></label></section><section className="summary-grid"><article className="metric"><span>{t(language,'符合條件的機構','Matching institutions')}</span><strong>{rows.length}</strong></article><article className="metric"><span>{t(language,'機構層級數','Institution levels')}</span><strong>{new Set(rows.map(record=>record.level).filter(Boolean)).size}</strong></article></section><section className="directory-card-grid">{rows.map(record=><article className="panel directory-card" key={record.id}><h3>{record.name}</h3><dl><div><dt>{t(language,'機構層級','Institution level')}</dt><dd>{record.level||'—'}</dd></div><div><dt>{t(language,'地址','Address')}</dt><dd>{record.address||'—'}</dd></div></dl><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.address)}`}>{t(language,'外部地圖查詢','External map lookup')}</a></article>)}</section></main>;
}
