import { useEffect, useMemo, useState } from 'react';
import type { Language } from './types';

type RecordItem={period:string;approvedCapacity:number|null;actualPlacements:number|null;serviceVisits:number|null};
const t=(language:Language,zh:string,en:string)=>language==='zh'?zh:en;
const utilization=(record:RecordItem)=>record.approvedCapacity&&record.actualPlacements!==null?record.actualPlacements/record.approvedCapacity:null;

export default function DisabilityWelfareServices({language}:{language:Language}) {
  const[records,setRecords]=useState<RecordItem[]>([]);const[period,setPeriod]=useState('all');
  useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/disability-welfare-services/records.json`).then(response=>response.json()).then(setRecords);},[]);
  const rows=useMemo(()=>records.filter(record=>period==='all'||record.period===period),[records,period]);const latest=rows.at(-1);
  return <main className="overview appeal-trends"><section className="hero"><p className="eyebrow">{t(language,'社會福利 · 服務量統計','Social Welfare · Service Statistics')}</p><h2>{t(language,'身心障礙福利服務','Disability Welfare Services')}</h2><p className="notice">{t(language,'容量使用情形僅為描述性統計，不代表未滿足需求、個人適用性或服務品質。','Capacity utilization is descriptive only; it does not measure unmet demand, individual suitability, or service quality.')}</p></section><section className="filter-panel health-filters"><label>{t(language,'期間','Period')}<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="all">{t(language,'全部','All')}</option>{records.map(record=><option key={record.period}>{record.period}</option>)}</select></label></section>{latest&&<section className="summary-grid">{[[t(language,'最新期間','Latest period'),latest.period],[t(language,'核定容量','Approved capacity'),latest.approvedCapacity??'—'],[t(language,'實際安置人數','Actual placements'),latest.actualPlacements??'—'],[t(language,'容量使用率','Capacity utilization'),utilization(latest)===null?'—':`${(utilization(latest)!*100).toFixed(1)}%`],[t(language,'服務人次','Service visits'),latest.serviceVisits??'—']].map(([name,value])=><article className="metric" key={String(name)}><span>{name}</span><strong>{String(value)}</strong></article>)}</section>}<section className="panel table-wrap"><table><thead><tr>{[t(language,'期間','Period'),t(language,'核定容量','Approved capacity'),t(language,'實際安置人數','Actual placements'),t(language,'使用率','Utilization'),t(language,'服務人次','Service visits')].map(name=><th key={name}>{name}</th>)}</tr></thead><tbody>{[...rows].reverse().map(record=><tr key={record.period}><td>{record.period}</td><td>{record.approvedCapacity??'—'}</td><td>{record.actualPlacements??'—'}</td><td>{utilization(record)===null?'—':`${(utilization(record)!*100).toFixed(1)}%`}</td><td>{record.serviceVisits??'—'}</td></tr>)}</tbody></table></section></main>;
}
