import { useMemo, useState } from 'react';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import type { ElectricalInspectionMaintenanceBusinessRecord, Language } from './types';

const statusLabel: Record<string, Record<Language, string>> = {
  active: { zh: '來源登載：營業中／有效', en: 'Source-recorded active' },
  suspended: { zh: '來源登載：停業／暫停', en: 'Source-recorded suspended' },
  revoked: { zh: '來源登載：撤銷', en: 'Source-recorded revoked' },
  cancelled: { zh: '來源登載：註銷／廢止', en: 'Source-recorded cancelled' },
  unknown: { zh: '來源登載：未分類', en: 'Source-recorded unknown' },
};
const missing = (value: string | null | undefined) => value || '—';
const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;

function download(rows: ElectricalInspectionMaintenanceBusinessRecord[], includeSource: boolean) {
  const header = ['Business', 'Certificate number', 'Business registration number', 'Source-recorded status', 'District', 'Business address', 'Approval date', 'Approval document', 'Longitude raw', 'Latitude raw'];
  const body = rows.map((record) => [record.businessName, record.certificateNumber, record.businessRegistrationNumber, record.registrationStatusRaw, record.districtName, record.businessAddress, record.approvalDateRaw, record.approvalDocumentNumber, record.longitudeRaw, record.latitudeRaw]);
  const sourceColumns = includeSource ? [...new Set(rows.flatMap((record) => Object.keys(record.originalValues)))].filter((column) => column !== '負責人姓名') : [];
  const content = [header.concat(sourceColumns), ...body.map((row, index) => row.concat(sourceColumns.map((column) => rows[index].originalValues[column] ?? '')))].map((row) => row.map(csvCell).join(',')).join('\n');
  const url = URL.createObjectURL(new Blob([`\uFEFF${content}`], { type: 'text/csv;charset=utf-8' }));
  const link = document.createElement('a'); link.href = url; link.download = 'taipei-electrical-inspection-maintenance-businesses.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0);
}

export default function ElectricalInspectionMaintenanceBusinesses({ records, language }: { records: ElectricalInspectionMaintenanceBusinessRecord[]; language: Language }) {
  const [district, setDistrict] = useState('all'); const [status, setStatus] = useState('all'); const [year, setYear] = useState('all'); const [coordinates, setCoordinates] = useState('all'); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState<'businessName' | 'approvalDate' | 'districtName'>('businessName'); const [includeSource, setIncludeSource] = useState(false);
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return records.filter((record) => (district === 'all' || record.districtName === district)
      && (status === 'all' || record.registrationStatus === status)
      && (year === 'all' || record.approvalDate?.slice(0, 4) === year)
      && (coordinates === 'all' || (coordinates === 'valid' ? record.hasValidCoordinates : !record.hasValidCoordinates))
      && (!needle || [record.businessName, record.certificateNumber, record.businessRegistrationNumber, record.businessAddress, record.districtName, record.registrationStatusRaw, record.approvalDocumentNumber].join(' ').toLowerCase().includes(needle)));
  }, [coordinates, district, query, records, status, year]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => (a[sort] || '').localeCompare(b[sort] || '', 'zh-Hant')), [filtered, sort]);
  const pageSize = 10; const pageCount = Math.max(1, Math.ceil(sorted.length / pageSize)); const visible = sorted.slice((page - 1) * pageSize, page * pageSize);
  const districts = [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort(); const years = [...new Set(records.map((record) => record.approvalDate?.slice(0, 4)).filter(Boolean))].sort().reverse(); const mapped = filtered.filter((record) => record.hasValidCoordinates && record.latitude !== null && record.longitude !== null);
  const label = (zh: string, en: string) => language === 'zh' ? zh : en;
  const copy = (text: string) => navigator.clipboard?.writeText(text);
  const card = (name: string, value: string | number) => <article className="metric" key={name}><span>{name}</span><strong>{value}</strong></article>;
  const distribution = <section className="panel"><h3>{label('行政區分布', 'District Distribution')}</h3>{[...new Set(records.map((record) => record.districtName || label('未解析行政區', 'Unresolved district')))].map((item) => <div className="bar-row" key={item}><span>{item}</span><div><i style={{ width: `${(records.filter((record) => (record.districtName || label('未解析行政區', 'Unresolved district')) === item).length / Math.max(records.length, 1)) * 100}%` }} /></div><b>{records.filter((record) => (record.districtName || label('未解析行政區', 'Unresolved district')) === item).length}</b></div>)}</section>;
  return <main className="overview tobacco-control">
    <section className="hero"><p className="eyebrow">Taipei City · Economic Development</p><h2>{label('尋找用電設備檢驗維護業', 'Find a Registered Business')}</h2><p className="notice">{label('本資料為臺北市用電設備檢驗維護業登記清冊，反映來源更新時的行政紀錄；並非即時資格、營運、服務能力、價格、保險或推薦資訊。', 'This registry reflects source administrative records at the update time. It is not real-time qualification, operation, availability, pricing, insurance, service-quality, or recommendation information.')}</p></section>
    <section className="filter-panel health-filters">
      <label>{label('行政區', 'District')}<select value={district} onChange={(event) => { setDistrict(event.target.value); setPage(1); }}><option value="all">{label('全部', 'All')}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label>{label('來源登載狀態', 'Source-recorded status')}<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="all">{label('全部', 'All')}</option>{Object.keys(statusLabel).map((item) => <option value={item} key={item}>{statusLabel[item][language]}</option>)}</select></label>
      <label>{label('核設年份', 'Approval year')}<select value={year} onChange={(event) => { setYear(event.target.value); setPage(1); }}><option value="all">{label('全部', 'All')}</option>{years.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label>{label('座標', 'Coordinates')}<select value={coordinates} onChange={(event) => { setCoordinates(event.target.value); setPage(1); }}><option value="all">{label('全部', 'All')}</option><option value="valid">{label('有效座標', 'Valid coordinates')}</option><option value="invalid">{label('未驗證／無效', 'Unverified or invalid')}</option></select></label>
      <label className="search-field">{label('搜尋', 'Search')}<input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder={label('名稱、證號、統編、地址或核設文號', 'Business, certificate, registration no., address, or document')} /></label>
    </section>
    <section className="summary-grid">
      {card(label('來源紀錄', 'Source records'), records.length)}{card(label('不同業者名稱', 'Unique business names'), new Set(records.map((record) => record.businessName)).size)}{card(label('不同證號', 'Unique certificates'), new Set(records.map((record) => record.certificateNumber).filter(Boolean)).size)}{card(label('涵蓋行政區', 'Districts covered'), districts.length)}{card(label('來源登載有效', 'Source-recorded active'), records.filter((record) => record.registrationStatus === 'active').length)}{card(label('其他／未知狀態', 'Other or unknown status'), records.filter((record) => record.registrationStatus !== 'active').length)}{card(label('可用地圖座標', 'Valid map coordinates'), records.filter((record) => record.hasValidCoordinates).length)}{card(label('已解析核設日期', 'Parsed approval dates'), records.filter((record) => record.approvalDate).length)}
    </section>
    <section className="panel"><h3>{label('地圖', 'Map')}</h3><p>{label(`目前篩選結果中 ${mapped.length} 筆可安全繪製；其餘 ${filtered.length - mapped.length} 筆保留於清冊。官方 CSV 的 X／Y 值為投影座標範圍，但資料集詮釋資料未確認座標參考系統，因此未轉換或繪製，以避免錯置。`, `${mapped.length} filtered records can be safely mapped; ${filtered.length - mapped.length} remain in the directory. The CSV X/Y values appear projected, but the dataset metadata does not confirm a coordinate reference system, so they are not converted or plotted.`)}</p><MapContainer center={[25.0478, 121.5319]} zoom={11} className="map-canvas" scrollWheelZoom><TileLayer url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" attribution="© OpenStreetMap contributors" />{mapped.map((record) => <Marker key={record.id} position={[record.latitude!, record.longitude!]}><Popup><strong>{record.businessName}</strong><br />{statusLabel[record.registrationStatus][language]}<br />{missing(record.districtName)} · {missing(record.businessAddress)}<br />{label('證號：', 'Certificate: ')}{missing(record.certificateNumber)}<br />{label('核設日期：', 'Approval date: ')}{missing(record.approvalDateRaw)}<br /><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`} target="_blank" rel="noreferrer">{label('外部地圖文字查詢', 'External map lookup')}</a></Popup></Marker>)}</MapContainer></section>
    <section className="summary-grid">{card(label('篩選結果', 'Filtered results'), filtered.length)}{card(label('未解析行政區', 'Unresolved districts'), filtered.filter((record) => !record.districtName).length)}{card(label('無有效座標', 'No valid coordinates'), filtered.filter((record) => !record.hasValidCoordinates).length)}{card(label('缺少完整識別欄位', 'Incomplete identifiers'), filtered.filter((record) => !record.certificateNumber || !record.businessRegistrationNumber).length)}</section>
    {distribution}
    <section className="panel"><h3>{label('來源登載狀態', 'Registration Status')}</h3>{Object.keys(statusLabel).map((item) => <div className="bar-row" key={item}><span>{statusLabel[item][language]}</span><div><i style={{ width: `${(filtered.filter((record) => record.registrationStatus === item).length / Math.max(filtered.length, 1)) * 100}%` }} /></div><b>{filtered.filter((record) => record.registrationStatus === item).length}</b></div>)}</section>
    <section className="panel"><h3>{label('核設時間軸', 'Approval Timeline')}</h3>{years.map((item) => <div className="bar-row" key={item}><span>{item}</span><div><i style={{ width: `${(filtered.filter((record) => record.approvalDate?.startsWith(item!)).length / Math.max(filtered.length, 1)) * 100}%` }} /></div><b>{filtered.filter((record) => record.approvalDate?.startsWith(item!)).length}</b></div>)}</section>
    <section className="panel table-wrap"><h3>{label('業者清冊', 'Business Directory')}</h3><div className="filter-panel"><label>{label('排序', 'Sort')}<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="businessName">{label('業者名稱', 'Business')}</option><option value="approvalDate">{label('核設日期', 'Approval date')}</option><option value="districtName">{label('行政區', 'District')}</option></select></label><label><input type="checkbox" checked={includeSource} onChange={(event) => setIncludeSource(event.target.checked)} />{label('匯出完整來源欄位（不含負責人姓名）', 'Include full source fields (responsible person excluded)')}</label><button type="button" onClick={() => download(sorted, includeSource)}>{label('下載篩選 CSV', 'Download filtered CSV')}</button></div><table><thead><tr>{[label('業者', 'Business'), label('證號', 'Certificate'), label('統編', 'Registration no.'), label('來源登載狀態', 'Status'), label('行政區', 'District'), label('營業地址', 'Address'), label('核設日期', 'Approval date'), label('核設文號', 'Approval document'), label('地圖', 'Map')].map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{visible.map((record) => <tr key={record.id}><td><strong>{missing(record.businessName)}</strong><details><summary>{label('來源細節', 'Source details')}</summary><p>{label('負責人姓名：', 'Responsible person: ')}{missing(record.responsiblePersonName)}</p><p>{label('原始狀態：', 'Raw status: ')}{missing(record.registrationStatusRaw)}</p><p>{label('原始座標：', 'Raw coordinates: ')}{missing(record.longitudeRaw)}, {missing(record.latitudeRaw)}</p><button type="button" onClick={() => copy(JSON.stringify(record.originalValues, null, 2))}>{label('複製來源欄位', 'Copy source fields')}</button></details></td><td>{missing(record.certificateNumber)} <button type="button" aria-label={label('複製證號', 'Copy certificate')} onClick={() => copy(record.certificateNumber)}>⧉</button></td><td>{missing(record.businessRegistrationNumber)} <button type="button" aria-label={label('複製統編', 'Copy registration number')} onClick={() => copy(record.businessRegistrationNumber)}>⧉</button></td><td>{statusLabel[record.registrationStatus][language]}<br /><small>{record.registrationStatusRaw}</small></td><td>{missing(record.districtName)}</td><td>{missing(record.businessAddress)}</td><td>{missing(record.approvalDateRaw)}</td><td>{missing(record.approvalDocumentNumber)}</td><td><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`} target="_blank" rel="noreferrer">{label('文字查詢', 'Text lookup')}</a></td></tr>)}</tbody></table><div className="filter-panel"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{label('上一頁', 'Previous')}</button><span>{page} / {pageCount}</span><button type="button" disabled={page >= pageCount} onClick={() => setPage((value) => value + 1)}>{label('下一頁', 'Next')}</button></div></section>
    <section className="panel"><h3>{label('資料品質', 'Data Quality')}</h3><p>{label(`所有 ${records.length} 筆紀錄均保留。未解析行政區 ${records.filter((record) => !record.districtName).length} 筆；未確認可繪製座標 ${records.filter((record) => !record.hasValidCoordinates).length} 筆；未知狀態 ${records.filter((record) => record.registrationStatus === 'unknown').length} 筆。轉換僅移除完全相同的重複列。`, `All ${records.length} records are retained. ${records.filter((record) => !record.districtName).length} do not contain a resolvable district, ${records.filter((record) => !record.hasValidCoordinates).length} do not have confirmed plottable coordinates, and ${records.filter((record) => record.registrationStatus === 'unknown').length} have an unknown status. Conversion removes exact duplicate rows only.`)}</p></section>
    <section className="panel"><h3>{label('資料說明', 'Data Notes')}</h3><p>{label('資料來源：臺北市資料大平臺「臺北市用電設備檢驗維護業登記資料」，資料檔更新日期 2026-07-03，詮釋資料更新日期 2026-07-06。登記資料不等同於現時資格或特定工程適任性；委託前請向業者及主管機關確認。', 'Source: Taipei Open Data, “Taipei Electrical Equipment Inspection and Maintenance Business Registration Data.” File updated 2026-07-03; metadata updated 2026-07-06. Registry inclusion does not establish current qualification or fitness for a particular job; confirm with the business and competent authorities before engagement.')}</p></section>
  </main>;
}
