import { useEffect, useMemo, useState } from 'react';
import type { Language } from './types';

type RecordItem = { id:string; caseNumber:string; dispositionDateRaw:string; dispositionDate:string|null; dispositionYear:number|null; caseStatusRaw:string; cadastralDistrict:string; cadastralReference:string; violationAreaSqm:number|null; violationTypeRaw:string; hasTwoYearDevelopmentSuspension:boolean|null; suspensionExpiryDate:string|null; fineAmountTwd:number|null; dataQualityWarnings:string[]; originalValues:Record<string,string> };
type Metadata = { coverageEnd:string; sourceFileUpdatedAt:string; dataQuality:Record<string,number> };
const base=`${import.meta.env.BASE_URL}data/soil-water-conservation-violations/`;
const text=(language:Language,zh:string,en:string)=>language==='zh'?zh:en;
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?sorted[Math.floor(sorted.length/2)]:null};
const amount=(value:number|null,prefix='',suffix='')=>value===null?'—':`${prefix}${value.toLocaleString()}${suffix}`;

export default function SoilWaterConservationViolations({language}:{language:Language}) {
  const [records,setRecords]=useState<RecordItem[]>([]); const [metadata,setMetadata]=useState<Metadata|null>(null);
  const [view,setView]=useState('overview'); const [year,setYear]=useState('all'); const [status,setStatus]=useState('all'); const [type,setType]=useState('all'); const [district,setDistrict]=useState('all'); const [suspension,setSuspension]=useState('all'); const [query,setQuery]=useState(''); const [page,setPage]=useState(0);
  useEffect(()=>{Promise.all([fetch(base+'records.json').then(r=>r.json()),fetch(base+'metadata.json').then(r=>r.json())]).then(([items,meta])=>{setRecords(items);setMetadata(meta)})},[]);
  const choices=(key:keyof RecordItem)=>[...new Set(records.map(item=>item[key]).filter(Boolean) as string[])].sort();
  const years=choices('dispositionYear'), statuses=choices('caseStatusRaw'), types=choices('violationTypeRaw'), districts=choices('cadastralDistrict');
  const rows=useMemo(()=>records.filter(item=>(year==='all'||String(item.dispositionYear)===year)&&(status==='all'||item.caseStatusRaw===status)&&(type==='all'||item.violationTypeRaw===type)&&(district==='all'||item.cadastralDistrict===district)&&(suspension==='all'||(suspension==='yes'?item.hasTwoYearDevelopmentSuspension===true:suspension==='no'?item.hasTwoYearDevelopmentSuspension===false:item.suspensionExpiryDate!==null))&&(!query||[item.caseNumber,item.cadastralReference,item.violationTypeRaw,item.caseStatusRaw].join(' ').toLowerCase().includes(query.toLowerCase()))),[records,year,status,type,district,suspension,query]);
  const aggregate=(key:keyof RecordItem,metric:(item:RecordItem)=>number=()=>1)=>Object.entries(rows.reduce<Record<string,number>>((result,item)=>{const name=String(item[key]??'未提供');result[name]=(result[name]??0)+metric(item);return result},{})).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count);
  const byYear=aggregate('dispositionYear'), byType=aggregate('violationTypeRaw'), byDistrict=aggregate('cadastralDistrict'); const areas=rows.flatMap(item=>item.violationAreaSqm===null?[]:[item.violationAreaSqm]); const fines=rows.flatMap(item=>item.fineAmountTwd===null?[]:[item.fineAmountTwd]);
  const label=(zh:string,en:string)=>text(language,zh,en);
  const exportCsv=()=>{const header=['Case number','Disposition date','Status','Cadastral reference','Violation type','Area sqm','Two-year suspension','Suspension expiry','Fine TWD','Warnings'];const csv=[header,...rows.map(item=>[item.caseNumber,item.dispositionDateRaw,item.caseStatusRaw,item.cadastralReference,item.violationTypeRaw,item.violationAreaSqm??'',item.hasTwoYearDevelopmentSuspension===true?'Yes':item.hasTwoYearDevelopmentSuspension===false?'No':'',item.suspensionExpiryDate??'',item.fineAmountTwd??'',item.dataQualityWarnings.join(';')])].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='soil-water-conservation-violations-historical.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0)};
  if(!metadata)return <main className="status-screen">Loading…</main>;
  const tabs=[['overview','總覽','Overview'],['explorer','案件查詢','Case Explorer'],['types','違規類別','Violation Types'],['district','地籍區分析','District Analysis'],['area','違規面積','Violation Area'],['fines','罰鍰與處分','Fines & Enforcement'],['suspension','暫停開發','Development Suspensions'],['trends','歷史趨勢','Historical Trends'],['quality','資料品質','Data Quality'],['notes','資料說明','Data Notes']];
  return <main className="overview appeal-trends"><section className="hero"><p className="eyebrow">Hillside Safety · Soil Conservation · Historical Enforcement</p><h2>{label('水土保持法違規案件','Soil and Water Conservation Violation Cases')}</h2><p className="notice">{label('現行資料集收錄至 2022 年 12 月 31 日。這是歷史執法資料，不能證明個別地號目前仍違規或仍受開發限制。','The current dataset covers records through December 31, 2022. It is historical enforcement data and does not establish that an individual parcel currently remains in violation or subject to development restrictions.')}</p></section><div className="tabs sub-tabs">{tabs.map(([id,zh,en])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label(zh,en)}</button>)}</div><section className="filter-panel health-filters"><Filter label={label('處分年度','Disposition year')} value={year} onChange={setYear} choices={years} all={label('全部','All')}/><Filter label={label('案件狀態','Case status')} value={status} onChange={setStatus} choices={statuses} all={label('全部','All')}/><Filter label={label('違規類別','Violation type')} value={type} onChange={setType} choices={types} all={label('全部','All')}/><Filter label={label('地籍區','Cadastral district')} value={district} onChange={setDistrict} choices={districts} all={label('全部','All')}/><Filter label={label('暫停開發','Development suspension')} value={suspension} onChange={setSuspension} choices={[['yes',label('有紀錄','Recorded')],['no',label('無紀錄','Not recorded')],['expiry',label('有到期日','Has expiry')]]} all={label('全部','All')}/><label className="search-field">{label('搜尋','Search')}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={label('案號、地籍或類別','Case, cadastral reference, or type')}/></label></section>
  {view==='overview'&&<><section className="summary-grid">{[[label('歷史案件','Recorded historical cases'),rows.length],[label('不重複案號','Unique case numbers'),new Set(rows.map(item=>item.caseNumber).filter(Boolean)).size],[label('地籍區數','Cadastral districts'),new Set(rows.map(item=>item.cadastralDistrict).filter(Boolean)).size],[label('有效違規面積','Valid recorded area'),amount(areas.reduce((a,b)=>a+b,0),'',' m²')],[label('面積中位數','Median area'),amount(median(areas),'',' m²')],[label('來源罰鍰總額','Total source-recorded fines'),amount(fines.reduce((a,b)=>a+b,0),'NT$')],[label('罰鍰中位數','Median fine'),amount(median(fines),'NT$')],[label('有兩年暫停紀錄','Recorded two-year suspensions'),rows.filter(item=>item.hasTwoYearDevelopmentSuspension).length],[label('最早處分年','Earliest disposition year'),years[0]??'—'],[label('最新處分年','Latest disposition year'),years.at(-1)??'—'],[label('資料收錄迄日','Dataset coverage end'),metadata.coverageEnd]].map(([name,value])=><article className="metric" key={String(name)}><span>{name}</span><strong>{String(value)}</strong></article>)}</section><section className="panel"><h3>{label('動態洞察','Insights')}</h3><p>{byYear[0]&&label(`${byYear[0].name}年在目前篩選中有最多歷史案件紀錄（${byYear[0].count} 件）。`,`${byYear[0].name} has the most recorded cases in the current filter (${byYear[0].count}).`)}</p><p>{byType[0]&&label(`${byType[0].name}是目前篩選中最常見的違規類別（${byType[0].count} 件）；出現頻率不代表嚴重程度。`,`${byType[0].name} is the most common violation type in the current filter (${byType[0].count} cases); frequency does not indicate severity.`)}</p></section></>}
  {view==='types'&&<Bars title={label('案件數依違規類別','Cases by violation type')} data={byType}/>} {view==='district'&&<Bars title={label('案件數依地籍區','Recorded cases by cadastral district')} data={byDistrict}/>} {view==='area'&&<Bars title={label('各地籍區有效違規面積','Valid recorded violation area by cadastral district')} data={aggregate('cadastralDistrict',item=>item.violationAreaSqm??0)} suffix=" m²"/>} {view==='fines'&&<Bars title={label('依違規類別的來源罰鍰總額','Total source-recorded fine by violation type')} data={aggregate('violationTypeRaw',item=>item.fineAmountTwd??0)} prefix="NT$"/>} {view==='suspension'&&<Bars title={label('依違規類別的兩年暫停開發紀錄','Recorded two-year development suspensions by violation type')} data={aggregate('violationTypeRaw',item=>item.hasTwoYearDevelopmentSuspension?1:0)}/>} {view==='trends'&&<Bars title={label('依處分年度的歷史案件','Recorded historical cases by disposition year')} data={byYear}/>} 
  {view==='explorer'&&<section className="panel table-wrap"><button onClick={exportCsv}>{label('下載篩選 CSV','Download filtered CSV')}</button><table><thead><tr>{[label('案號','Case number'),label('處分日期','Disposition date'),label('狀態','Status'),label('地籍參考','Cadastral reference'),label('違規類別','Violation type'),label('面積','Area'),label('兩年暫停','Two-year suspension'),label('到期日','Expiry'),label('罰鍰','Fine')].map(name=><th key={name}>{name}</th>)}</tr></thead><tbody>{rows.slice(page*20,page*20+20).map(item=><tr key={item.id}><td><details><summary>{item.caseNumber||'—'}</summary><pre>{JSON.stringify(item.originalValues,null,2)}</pre></details></td><td>{(item.dispositionDate??item.dispositionDateRaw)||'—'}</td><td>{item.caseStatusRaw||'—'}</td><td>{item.cadastralReference||'—'}</td><td>{item.violationTypeRaw||'—'}</td><td>{amount(item.violationAreaSqm,'',' m²')}</td><td>{item.hasTwoYearDevelopmentSuspension===true?label('有紀錄','Recorded'):item.hasTwoYearDevelopmentSuspension===false?label('無紀錄','Not recorded'):'—'}</td><td>{item.suspensionExpiryDate??'—'}</td><td>{amount(item.fineAmountTwd,'NT$')}</td></tr>)}</tbody></table><div className="filter-panel"><button disabled={!page} onClick={()=>setPage(page-1)}>{label('上一頁','Previous')}</button><span>{page+1} / {Math.max(1,Math.ceil(rows.length/20))}</span><button disabled={(page+1)*20>=rows.length} onClick={()=>setPage(page+1)}>{label('下一頁','Next')}</button></div></section>}
  {view==='quality'&&<section className="panel"><h3>{label('資料品質','Data Quality')}</h3><ul>{Object.entries(metadata.dataQuality).map(([name,value])=><li key={name}>{name}: <strong>{value}</strong></li>)}</ul></section>}{view==='notes'&&<section className="panel"><h3>{label('資料說明與限制','Data notes and limitations')}</h3><p>{label('本資料集為臺北市水土保持法違規案件的歷史行政紀錄。它不是現況地籍、執法、土地使用或安全判定。','This dataset contains historical administrative records of Soil and Water Conservation Act violation cases in Taipei. It is not a current cadastral, enforcement, land-use, or safety determination.')}</p><p>{label('請向大地工程處、地政與其他主管機關確認任何土地交易、開發、施工或法律決策所需的現況資訊。','Confirm current information with the Geotechnical Engineering Office, land authorities, and other competent agencies before land, development, construction, or legal decisions.')}</p><a href="https://data.taipei/dataset/detail?id=e7b8404d-3742-4157-98fd-e101b40ba5c7" target="_blank" rel="noreferrer">{label('官方資料來源','Official source')}</a> · {label('檔案更新','File update')}: {metadata.sourceFileUpdatedAt}</section>}</main>;
}
function Filter({label,value,onChange,choices,all}:{label:string;value:string;onChange:(value:string)=>void;choices:Array<string|[string,string]>;all:string}) { return <label>{label}<select value={value} onChange={event=>onChange(event.target.value)}><option value="all">{all}</option>{choices.map(choice=>{const [value,label]=Array.isArray(choice)?choice:[choice,choice];return <option key={value} value={value}>{label}</option>})}</select></label> }
function Bars({title,data,prefix='',suffix=''}:{title:string;data:{name:string;count:number}[];prefix?:string;suffix?:string}) { const max=Math.max(...data.map(item=>item.count),1);return <section className="panel"><h3>{title}</h3>{data.filter(item=>item.count).map(item=><div className="bar-row" key={item.name}><span>{item.name}</span><div><i style={{width:`${item.count/max*100}%`}}/></div><b>{prefix}{item.count.toLocaleString()}{suffix}</b></div>)}</section> }
